### ISSUE TITLE
Portfolio on Raspberry pi

### ISSUE THREAD

**Issue by LeePaka** [omdv/robinhood-portfolio#1]
Hi, 
I'm the guy who was taking help from you on the robinhood subreddit post and I'm currently trying to get it to run in docker on the rpi but while it creates the container, it never actually runs it; it just says exited. If I take out -d from the main command to get it to run not in the background, it gives me this error: "standard_init_linux.go:178: exec user process caused "exec format error"".

I did some research and I think this may be because the docker image is compiled for an x86 platform and the raspberry pi runs on ARM. Would this be fixed by recompiling the docker image?

Thanks for the help

**Comment by omdv** [comment]
You are right, it will not work on ARM. I'll create a new image based on [raspbian](https://hub.docker.com/r/resin/rpi-raspbian/) and see how other dependencies work out. Testing may be difficult - my RPI has been offline for a while. So once/if it compiles I'll add a revision for you to try.

**Comment by omdv** [comment]
BTW, was the other issue with connection resolved?

**Comment by LeePaka** [comment]
The connection issue was not resolved, did you ever end up trying to make an arm image?

**Comment by omdv** [comment]
Converting it to arm is possible, however pytables are not very well supported on arm at the moment. So it may be easier just to create a branch based on pickle or csv. Will try to look at it some point - somewhat busy now.

**Comment by omdv** [comment]
Not going to happen. Closing now.
