### ISSUE TITLE
Docker run fails.  No module named 'Robinhood'

### ISSUE THREAD

**Issue by frakman1** [omdv/robinhood-portfolio#11]
When I use the `docker run` command, I get this failure:

`docker run -e TIINGO_API_KEY=xxx  -p 8080:8080 --name robinhood omdv/robinhood-portfolio:ubuntu`

```python
Status: Downloaded newer image for omdv/robinhood-portfolio:ubuntu
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from backend.backend import BackendClass
  File "/robinhood-portfolio/backend/backend.py", line 5, in <module>
    from backend.robinhood_data import RobinhoodData
  File "/robinhood-portfolio/backend/robinhood_data.py", line 4, in <module>
    from Robinhood import Robinhood
ImportError: No module named 'Robinhood'
```

Running on Mac OSX 10.13.6 (High Sierra)
Docker version 19.03.2, build 6a30dfc

**Comment by rbdl1** [comment]
I tried this a couple of days ago too, in digital ocean, and had the same problem. At first we couldn't figure out what was going on because it seemed like the image wasn't even running, but it was the script inside the image that was halting somehow with errors, but I don't know enough about python to diagnose it. That all said, however, I would be very very appreciative if anyone figures out how to actually get this going!!!

**Comment by omdv** [comment]
Hi, thanks for submitting. I am not using it for few years, tried to rebuild docker image just now and found that `Robinhood` module is replaced with [pyrh](https://pypi.org/project/pyrh/#history). Will try to update everything. If module API hasn't changed it should not take long.

**Comment by rbdl1** [comment]
<3

**Comment by frakman1** [comment]
Is there a reason why the previous working docker image isn't on dockerhub? That way a historical working version would be available for everyone instead of having to build one today that doesn't work anymore.

**Comment by omdv** [comment]
Hey, quick update. First, I don't know why docker image was changed - most likely I triggered the build during last commit and you were the first who noticed. And I didn't have a proper CI/CD.

Now, as for fixing it. I am not using it myself for 3+ years. Started looking at the code - it is quite messy and uses obsoleted features of pandas. To be honest I have limited interest/time to fix it. Plus I don't think a lot of people use it. Will try to salvage and migrate it to Jupyter notebook inside docker first, which will make it easier to tinker with. Sorry. Will likely take a week or longer.

**Comment by frakman1** [comment]
That's OK. I'm not in a hurry. I've never used it so I only have the screenshot to go by. It looked cool so I thought I'd give it a shot. 

I did find a [similar project](https://github.com/bcwik9/robinhood-on-rails) written in Ruby on Rails that works that you might be interested in. 

Thank you for making this project and sharing it with the world. Much appreciated!

**Comment by rbdl1** [comment]
Well, I am staying tuned, as this package has a very unique functionality of portfolio analysis and visualization, which neither countless others which I have looked at do, nor the nonetheless interesting RoR one which @frakman1 has found above! :(

Please keep us posted, and if you have any more diagnostic updates as far as what is wrong, or what impacts that would have, even though I have very limited python knowledge, it might enable myself or someone entirely different to patch it up! Perhaps even if some features will be missing or broken, if I could even get some of this functionality from something that can run, I would be so grateful!

**Comment by rbdl1** [comment]
Hi @omdv , was wondering if there's any update on this, or suggested hacks that one might be able to use to get this running?

**Comment by omdv** [comment]
Hi @rbdl1. Sure, I made changes couple of weeks ago, but was sitting on them to add some testing. Check out the updated version.

Done:
- migrated away from Pandas panels finally and upgraded to latest versions
- reworked all calculations to get rid of tables and HDFstore, which will allow to use smaller version of docker images
- cleaned up code in few places

What was not done:
I haven't updated the actual flask portion, so currently the only way to use it is via [Robinhood jupyter notebook](https://github.com/omdv/robinhood-portfolio/blob/master/notebooks/Robinhood.ipynb). I'll update instructions and will recompile docker image with jupyter notebook and proper conda environment.

May rework flask part later. Will update docker image and instructions later next week.

**Comment by rbdl1** [comment]
@omdv, You are a legend. <3

**Comment by rbdl1** [comment]
Hey, was just wondering if there's any updates on this? :)

**Comment by omdv** [comment]
@rbdl1, I plan to update readme to indicate that it was converted to Jupyter notebook. Other than that - I don't think I will touch the flask part.

**Comment by rbdl1** [comment]
@omdv Okay, so what does this mean from an end-user then from an end-user perspective, then? Is this currently usable as is, or not quite yet? Thanks for working on it.

**Comment by omdv** [comment]
Hi, sorry for delay. It was usable since my previous reply. I added instructions. Will add docker way as well, although it may be an overkill if it runs just jupyter.
