### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by goodpunk6** [omdv/robinhood-portfolio#13]
Ok so I open that main file, and then what? How do I get my Robinhood api_key?? That notebook literally has no instructions. How does someone use this?

**Comment by omdv** [comment]
Someone uses this by reading Readme, which says: _Open main.ipynb, enter TIINGO api_key, Robinhood credentials, set demo_run variable to False to run with your data, execute all cells._

This said it is deprecated, don't have time to look after it any more.
