### ISSUE TITLE
Google API change?

### ISSUE THREAD

**Issue by freddawes** [omdv/robinhood-portfolio#2]
Getting error pandas_datareader._utils.RemoteDataError: No data fetched using 'GoogleDailyReader'

**Comment by omdv** [comment]
Yes, looks like it. Looking at it.

**Comment by omdv** [comment]
Switched to [morningstar](https://github.com/omdv/robinhood-portfolio/commit/e481db99a65639327ecfb9367ee26ef5981c67ed)
