### ISSUE TITLE
broke?

### ISSUE THREAD

**Issue by djv2** [omdv/robinhood-portfolio#3]
![7](https://user-images.githubusercontent.com/20608679/41520844-43379f4e-7295-11e8-86be-d79576f5ab59.jpg)

**Comment by omdv** [comment]
Most likely explanation is that RH changed the symbol for one of your stocks, so symbols saved locally do not match the RH API. If you use docker - you can try stopping and deleting the container (don't delete image to avoid re-download) and start a new container. It should pull the updated list of symbols.

Alternatively, if you want, post the list of stocks/symbols you have and I can check each of them manually.

**Comment by dremio-al** [comment]
Not using docker, deployed both in Windows & Linux machine. Any other thoughts/advice to fix? I haven't had this issue with other RH py scripts

**Comment by djv2** [comment]
Not using docker, deployed both in Windows & Linux machine. Any other thoughts/advice to fix? I haven't had this issue with other RH py scripts

**Comment by omdv** [comment]
I suspect the issue was that there were no dividend payouts, so dataframe was empty and as a result had no "instrument" field. Could you pull the latest version and try again?

**Comment by djv2** [comment]
Thanks for your quick reply. Making progress, the error disappears but now it is stuck downloading market data...

Downloading dividends from Robinhood
Downloading orders from Robinhood
Downloading market data for 20171108-20180618

It's been downloading for 30min+ now, doubt it really takes that long?

**Comment by omdv** [comment]
No, no way. Likely get's stuck somewhere because of empty dividends info. If I don't have ideas - may need to add verbosity to understand where it get's stuck.

**Comment by djv2** [comment]
Found where it gets stuck...

pf = web.DataReader(tickers, 'morningstar', start_date, end_date)

Maybe there's a ticker morningstar doesn't like?

**Comment by omdv** [comment]
Ah, it's totally possible. Getting stock data nowadays is difficult - I had to switch to morningstar after google killed it's API. You can check some more exotic tickers on their page.

Just to be sure, it is not something else - you can add `pause=1.0` to that call, it is in folder `backend/market_data.py` on line 41. I suspect that if you have a large list of tickers to pull morningstar may not like it, so we can try to increase the delay between requests. If this does not work - then it is likely some exotic ticker.

**Comment by djv2** [comment]
Added `pause=1.0`, no effect. 
Random question (simply because I'm not a smart coder) - 
I tried to see what tickers it's actually trying to check with a `print(tickers)` and it's passing an array in format `['ticker' 'ticker' 'ticker']`
I tested it manually with a small python script outside of yours and that seems to stall, the correct syntax is  `['ticker', 'ticker', 'ticker']` with a comma. Am I missing something?

**Comment by djv2** [comment]
I believe I found the exotic ticker, SESN. What do I do now? It's a valid ticker...

**Comment by omdv** [comment]
Yes, you are right, SESN does not go through, although I can see it on morningstar page actually - https://www.morningstar.com/stocks/xnas/sesn/quote.html. I use [external library](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html) to get quotes - I'll try to see why it is happening.

**Comment by omdv** [comment]
Submitted [issue](https://github.com/pydata/pandas-datareader/issues/544) to pandas-datareader. I looked at their code and morningstar url and don't see anything which could explain it. Hopefully they can address it. Cheers.
