### ISSUE TITLE
Issues updating data (running on docker)

### ISSUE THREAD

**Issue by hunter-san** [omdv/robinhood-portfolio#9]
Setup and initialization in docker run fine.  Reasonably experienced with python code, but new to docker and flask.  When I attempt to update Robinhood data with my login info (2FA disabled), I get this error:

> json.decoder.JSONDecodeError
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> Traceback (most recent call last)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2309, in __call__
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2295, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1741, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
> raise value
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
> raise value
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/robinhood-portfolio/app.py", line 104, in portfolio
> bc.update_robinhood_data(user, password)
> File "/robinhood-portfolio/backend/backend.py", line 121, in update_robinhood_data
> rd.download_robinhood_data(user, password)
> File "/robinhood-portfolio/backend/robinhood_data.py", line 188, in download_robinhood_data
> self._login(user, password)
> File "/robinhood-portfolio/backend/robinhood_data.py", line 25, in _login
> self.client.login(username=user, password=password)
> File "/robinhood-portfolio/backend/robinhood_api.py", line 73, in login
> res = res.json()
> File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 897, in json
> return complexjson.loads(self.text, **kwargs)
> File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
> To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.
> 
> You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
> 
> dump() shows all variables in the frame
> dump(obj) dumps all that's known about the object

Any thoughts on how to fix this?

**Comment by omdv** [comment]
I am getting the same. Likely some changes in robinhood API. Let me investigate.

**Comment by omdv** [comment]
Should be fixed now. Re-download the docker image or just clone the latest repo - both should be updated.
